const Data = [
    
    {id:"6", category:"Abraham Lincoln", body : "My father taught me to work; he did not teach me to love it.", by : "Abraham Lincoln" },
    {id:"7", category:"Abraham Lincoln", body : "Common looking people are the best in the world: that is the reason the Lord makes so many of them.", by : "Abraham Lincoln" },
    {id:"8", category:"Abraham Lincoln", body : "How many legs does a dog have if you call the tail a leg? Four. Calling a tail a leg doesn't make it a leg.", by : "Abraham Lincoln" },
    {id:"9", category:"Abraham Lincoln", body : "And in the end it's not the years in your life that count. It's the life in your years.", by : "Abraham Lincoln" },
    {id:"10", category:"Abraham Lincoln", body : "My experience has taught me that a man who has no vices has damned few virtues.", by : "Abraham Lincoln" },
    {id:"11", category:"Abraham Lincoln", body : "Will springs from the two elements of moral sense and self-interest.", by : "Abraham Lincoln" },
    {id:"12", category:"Abraham Lincoln", body : "I am a slow walker, but I never walk backwards.", by : "Abraham Lincoln" },
    {id:"13", category:"Abraham Lincoln", body : "I will prepare and some day my chance will come.", by : "Abraham Lincoln" },
    {id:"14", category:"Abraham Lincoln", body : "I never had a policy; I have just tried to do my very best each and every day.", by : "Abraham Lincoln" },
    {id:"15", category:"Abraham Lincoln", body : "If there is anything that a man can do well, I say let him do it. Give him a chance.", by : "Abraham Lincoln" },
    {id:"16", category:"Abraham Lincoln", body : "You cannot escape the responsibility of tomorrow by evading it today.", by : "Abraham Lincoln" },
    {id:"17", category:"Abraham Lincoln", body : "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", by : "Abraham Lincoln" },
    {id:"18", category:"Abraham Lincoln", body : "", by : "Abraham Lincoln" },
    {id:"19", category:"Abraham Lincoln", body : "I do not think much of a man who is not wiser today than he was yesterday.", by : "Abraham Lincoln" },
    {id:"20", category:"Abraham Lincoln", body : "People are just as happy as they make up their minds to be.", by : "Abraham Lincoln" },
    {id:"0", category:"Albert Einstein", body : "Life is like riding a bicycle. To keep your balance you must keep moving.", by : "Albert Einstein" },
    {id:"1", category:"Albert Einstein", body : "The important thing is not to stop questioning. Curiosity has its own reason for existing.", by : "Albert Einstein" },
    {id:"2", category:"Albert Einstein", body : "No problem can be solved from the same level of consciousness that created it.", by : "Albert Einstein" },
    {id:"3", category:"Albert Einstein", body : "Try not to become a man of success, but rather try to become a man of value.", by : "Albert Einstein" },
    {id:"21", category:"Albert Einstein", body : "Imagination is more important than knowledge.", by : "Albert Einstein" },
    {id:"22", category:"Albert Einstein", body : "The hardest thing in the world to understand is the income tax.", by : "Albert Einstein" },
    {id:"23", category:"Albert Einstein", body : "Reality is merely an illusion, albeit a very persistent one.", by : "Albert Einstein" },
    {id:"24", category:"Albert Einstein", body : "The only real valuable thing is intuition.", by : "Albert Einstein" },
    {id:"25", category:"Albert Einstein", body : "A person starts to live when he can live outside himself.", by : "Albert Einstein" },
    {id:"26", category:"Albert Einstein", body : "Weakness of attitude becomes weakness of character.", by : "Albert Einstein" },
    {id:"27", category:"Albert Einstein", body : "I never think of the future. It comes soon enough.", by : "Albert Einstein" },
    {id:"28", category:"Albert Einstein", body : "The eternal mystery of the world is its comprehensibility.", by : "Albert Einstein" },
    {id:"29", category:"Albert Einstein", body : "Sometimes one pays most for the things one gets for nothing.", by : "Albert Einstein" },
    {id:"30", category:"Albert Einstein", body : "Science without religion is lame. Religion without science is blind.", by : "Albert Einstein" },
    {id:"31", category:"Albert Einstein", body : "Anyone who has never made a mistake has never tried anything new.", by : "Albert Einstein" },
    {id:"32", category:"Albert Einstein", body : "Great spirits have often encountered violent opposition from weak minds.", by : "Albert Einstein" },
    {id:"33", category:"Albert Einstein", body : "Common sense is the collection of prejudices acquired by age eighteen.", by : "Albert Einstein" },
    {id:"34", category:"Albert Einstein", body : "Science is a wonderful thing if one does not have to earn one's living at it.", by : "Albert Einstein" },
    {id:"35", category:"Albert Einstein", body : "The secret to creativity is knowing how to hide your sources.", by : "Albert Einstein" },
    {id:"36", category:"Albert Einstein", body : "The only thing that interferes with my learning is my education.", by : "Albert Einstein" },
    {id:"37", category:"Albert Einstein", body : "God does not care about our mathematical difficulties. He integrates empirically.", by : "Albert Einstein" },
    {id:"38", category:"Albert Einstein", body : "The whole of science is nothing more than a refinement of everyday thinking.", by : "Albert Einstein" },
    {id:"39", category:"Albert Einstein", body : "Technological progress is like an axe in the hands of a pathological criminal.", by : "Albert Einstein" },
    {id:"40", category:"Albert Einstein", body : "Peace cannot be kept by force. It can only be achieved by understanding.", by : "Albert Einstein" },
    {id:"41", category:"Albert Einstein", body : "The most incomprehensible thing about the world is that it is comprehensible.", by : "Albert Einstein" },
    {id:"42", category:"Albert Einstein", body : "Education is what remains after one has forgotten everything he learned in school.", by : "Albert Einstein" },
    {id:"43", category:"Albert Einstein", body : "Do not worry about your difficulties in Mathematics. I can assure you mine are still greater.", by : "Albert Einstein" },
    {id:"44", category:"Albert Einstein", body : "Equations are more important to me, because politics is for the present, but an equation is something for eternity.", by : "Albert Einstein" },
    {id:"45", category:"Albert Einstein", body : "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", by : "Albert Einstein" },
    {id:"46", category:"Albert Einstein", body : "As far as the laws of mathematics refer to reality, they are not certain, as far as they are certain, they do not refer to reality.", by : "Albert Einstein" },
    {id:"47", category:"Albert Einstein", body : "The fear of death is the most unjustified of all fears, for there's no risk of accident for someone who's dead.", by : "Albert Einstein" },
    {id:"48", category:"Albert Einstein", body : "In order to form an immaculate member of a flock of sheep one must, above all, be a sheep.", by : "Albert Einstein" },
    {id:"49", category:"Anthony Robbins", body : "A real decision is measured by the fact that you've taken a new action. If there's no action, you haven't truly decided.", by : "Anthony Robbins" },
    {id:"50", category:"Anthony Robbins", body : "Commit to CANI! - Constant And Never-ending Improvement.", by : "Anthony Robbins" },
    {id:"51", category:"Anthony Robbins", body : "For changes to be of any true value, they've got to be lasting and consistent.", by : "Anthony Robbins" },
    {id:"52", category:"Anthony Robbins", body : "If you do what you've always done, you'll get what you've always gotten.", by : "Anthony Robbins" },
    {id:"53", category:"Anthony Robbins", body : "In life you need either inspiration or desperation.", by : "Anthony Robbins" },
    {id:"54", category:"Anthony Robbins", body : "It is in your moments of decision that your destiny is shaped.", by : "Anthony Robbins" },
    {id:"55", category:"Anthony Robbins", body : "It is not what we get. But who we become, what we contribute... that gives meaning to our lives.", by : "Anthony Robbins" },
    {id:"56", category:"Anthony Robbins", body : "It not knowing what to do, it's doing what you know.", by : "Anthony Robbins" },
    {id:"57", category:"Anthony Robbins", body : "It's not the events of our lives that shape us, but our beliefs as to what those events mean.", by : "Anthony Robbins" },
    {id:"58", category:"Anthony Robbins", body : "Passion is the genesis of genius.", by : "Anthony Robbins" },
    {id:"59", category:"Anthony Robbins", body : "People are not lazy. They simply have impotent goals - that is, goals that do not inspire them.", by : "Anthony Robbins" },
    {id:"60", category:"Anthony Robbins", body : "Setting goals is the first step in turning the invisible into the visible.", by : "Anthony Robbins" },
    {id:"61", category:"Anthony Robbins", body : "The meeting of preparation with opportunity generates the offspring we call luck.", by : "Anthony Robbins" },
    {id:"62", category:"Anthony Robbins", body : "The path to success is to take massive, determined action.", by : "Anthony Robbins" },
    {id:"63", category:"Anthony Robbins", body : "The way we communicate with others and with ourselves ultimately determines the quality of our lives.", by : "Anthony Robbins" },
    {id:"64", category:"Anthony Robbins", body : "There is no such thing as failure. There are only results.", by : "Anthony Robbins" },
    {id:"65", category:"Anthony Robbins", body : "There's always a way - if you're committed.", by : "Anthony Robbins" },
    {id:"66", category:"Anthony Robbins", body : "There's no abiding success without commitment.", by : "Anthony Robbins" },
    {id:"67", category:"Anthony Robbins", body : "We aren't in an information age, we are in an entertainment age.", by : "Anthony Robbins" },
    {id:"68", category:"Anthony Robbins", body : "We can change our lives. We can do, have, and be exactly what we wish.", by : "Anthony Robbins" },
    {id:"69", category:"Anthony Robbins", body : "We will act consistently with our view of who we truly are, whether that view is accurate or not.", by : "Anthony Robbins" },
    {id:"70", category:"Anthony Robbins", body : "Whatever happens, take responsibility!", by : "Anthony Robbins" },
    {id:"71", category:"Anthony Robbins", body : "You always succeed in producing a result.", by : "Anthony Robbins" },
    {id:"72", category:"Brian Tracey", body : "The more credit you give away, the more will come back to you. The more you help others, the more they will want to help you.", by : "Brian Tracey" },
    {id:"73", category:"Brian Tracey", body : "It doesn't matter where you are coming from. All that matters is where you are going.", by : "Brian Tracey" },
    {id:"74", category:"Brian Tracey", body : "Relationships are the hallmark of the mature person.", by : "Brian Tracey" },
    {id:"75", category:"Brian Tracey", body : "Never say anything about yourself you do not want to come true.", by : "Brian Tracey" },
    {id:"76", category:"Brian Tracey", body : "The person we believe ourselves to be will always act in a manner consistent with our self-image.", by : "Brian Tracey" },
    {id:"77", category:"Brian Tracey", body : "We feel good about ourselves to the exact degree we feel in control of our lives.", by : "Brian Tracey" },
    {id:"78", category:"Brian Tracey", body : "You have within you right now, everything you need to deal with whatever the world can throw at you.", by : "Brian Tracey" },
    {id:"79", category:"Dale Carnegie", body : "Any fool can criticize, condemn, and complain -- and most fools do.", by : "Dale Carnegie" },
    {id:"80", category:"Dale Carnegie", body : "Remember happiness doesn't depend on who you are or what you have; it depends solely upon what you think.", by : "Dale Carnegie" },
    {id:"81", category:"Dale Carnegie", body : "Success is getting what you want. Happiness is wanting what you get.", by : "Dale Carnegie" },
    {id:"82", category:"Dale Carnegie", body : "Those convinced against their will are of the same opinion still.", by : "Dale Carnegie" },
    {id:"83", category:"Dale Carnegie", body : "I deal with the obvious. I present, reiterate and glorify the obvious -- because the obvious is what people need to be told.", by : "Dale Carnegie" },
    {id:"84", category:"Dale Carnegie", body : "The royal road to a man's heart is to talk to him about the things he treasures most.", by : "Dale Carnegie" },
    {id:"85", category:"Dale Carnegie", body : "If you want to be enthusiastic, act enthusiastic.", by : "Dale Carnegie" },
    {id:"86", category:"Dale Carnegie", body : "When fate hands us a lemon, let's try to make a lemonade.", by : "Dale Carnegie" },
    {id:"87", category:"Dale Carnegie", body : "The successful man will profit from his mistakes and try again in a different way.", by : "Dale Carnegie" },
    {id:"88", category:"Dale Carnegie", body : "Flaming enthusiasm, backed up by horse sense and persistence, is the quality that most frequently makes for success.", by : "Dale Carnegie" },
    {id:"89", category:"Dennis Waitley", body : "Mistakes are painful when they happen, but years later a collection of mistakes is what is called experience.", by : "Dennis Waitley" },
    {id:"90", category:"Dennis Waitley", body : "Expect the best, plan for the worst, and prepare to be surprised.", by : "Dennis Waitley" },
    {id:"91", category:"Dennis Waitley", body : "You must learn from your past mistakes, but not lean on your past successes.", by : "Dennis Waitley" },
    {id:"92", category:"Dennis Waitley", body : "It's not what you are that holds you back, it's what you think you are not.", by : "Dennis Waitley" },
    {id:"93", category:"Dennis Waitley", body : "Luck happens when opportunity encounters the prepared mind.", by : "Dennis Waitley" },
    {id:"94", category:"Dennis Waitley", body : "Losers make promises they often break. Winners make commitments they always keep.", by : "Dennis Waitley" },
    {id:"95", category:"Dennis Waitley", body : "Life is not accountable to us. We are accountable to life.", by : "Dennis Waitley" },
    {id:"96", category:"Dennis Waitley", body : "We have got to have a dream if we are going to make a dream come true.", by : "Dennis Waitley" },
    {id:"97", category:"Dennis Waitley", body : "Out of need springs desire, and out of desire springs the energy and the will to win.", by : "Dennis Waitley" },
    {id:"98", category:"Dennis Waitley", body : "Love is a daily, mutual exchange of value.", by : "Dennis Waitley" },
    {id:"99", category:"Dennis Waitley", body : "A smile is the light in your window that tells others that there is a caring, sharing person inside.", by : "Dennis Waitley" },
    {id:"100", category:"Dennis Waitley", body : "The greatest gifts you can give your children are the roots of responsibility and the wings of independence.", by : "Dennis Waitley" },
    {id:"4", category:"Donald Trump", body : "I try to learn from the past, but I plan for the future by focusing exclusively on the present. That's where the fun is.", by : "Donald Trump" },
    {id:"5", category:"Donald Trump", body : "The point is that you can't be too greedy.", by : "Donald Trump" },
    {id:"101", category:"Donald Trump", body : "A little more moderation would be good. Of course, my life hasn't exactly been one of moderation.", by : "Donald Trump" },
    {id:"102", category:"Donald Trump", body : "Sometimes by losing a battle you find a new way to win the war.", by : "Donald Trump" },
    {id:"103", category:"Donald Trump", body : "You have to think anyway, so why not think big?", by : "Donald Trump" },
    {id:"104", category:"Donald Trump", body : "Money was never a big motivation for me, except as a way to keep score. The real excitement is playing the game.", by : "Donald Trump" },
    {id:"105", category:"Donald Trump", body : "No dream is too big. No challenge is too great. Nothing we want for our future is beyond our reach.", by : "Donald Trump" },
    {id:"106", category:"Donald Trump", body : "I've always won, and I'm going to continue to win. And that's the way it is.", by : "Donald Trump" },
    {id:"107", category:"Donald Trump", body : "I like thinking big. If you're going to be thinking anything, you might as well think big.", by : "Donald Trump" },
    {id:"108", category:"Earl Nightingale", body : "Our attitude toward life determines life's attitude towards us.", by : "Earl Nightingale" },
    {id:"109", category:"Earl Nightingale", body : "People with goals succeed because they know where they're going.", by : "Earl Nightingale" },
    {id:"110", category:"Earl Nightingale", body : "Success is the progressive realization of a worthy goal or ideal.", by : "Earl Nightingale" },
    {id:"111", category:"Earl Nightingale", body : "Open your ears before you open your mouth, it may surprise your eyes!", by : "Earl Nightingale" },
    {id:"112", category:"Earl Nightingale", body : "Your world is a living expression of how you are using and have used your mind.", by : "Earl Nightingale" },
    {id:"113", category:"Earl Nightingale", body : "We can let circumstances rule us, or we can take charge and rule our lives from within.", by : "Earl Nightingale" },
    {id:"114", category:"Earl Nightingale", body : "We can help others in the world more by making the most of yourself than in any other way.", by : "Earl Nightingale" },
    {id:"115", category:"Earl Nightingale", body : "Whenever we're afraid, its because we don't know enough. If we understood enough, we would never be afraid.", by : "Earl Nightingale" },
    {id:"116", category:"Earl Nightingale", body : "Whatever we plant in our subconscious mind and nourish with repetition and emotion will one day become a reality.", by : "Earl Nightingale" },
    {id:"117", category:"Earl Nightingale", body : "We tend to live up to our expectations.", by : "Earl Nightingale" },
    {id:"118", category:"Earl Nightingale", body : "You'll find boredom where there is an absence of a good idea.", by : "Earl Nightingale" },
    {id:"119", category:"Earl Nightingale", body : "Creativity is a natural extension of our enthusiasm.", by : "Earl Nightingale" },
    {id:"120", category:"Earl Nightingale", body : "Everything in the world we want to do or get done, we must do with and through people.", by : "Earl Nightingale" },
    {id:"121", category:"Earl Nightingale", body : "Our first journey is to find that special place for us.", by : "Earl Nightingale" },
    {id:"122", category:"Jim Rohn", body : "For every disciplined effort there is a multiple reward.", by : "Jim Rohn" },
    {id:"123", category:"Jim Rohn", body : "Formal education will make you a living; self-education will make you a fortune.", by : "Jim Rohn" },
    {id:"124", category:"Jim Rohn", body : "Give whatever you are doing and whoever you are with the gift of your attention.", by : "Jim Rohn" },
    {id:"125", category:"Jim Rohn", body : "Words do two major things: They provide food for the mind and create light for understanding and awareness.", by : "Jim Rohn" },
    {id:"126", category:"Jim Rohn", body : "Discipline is the bridge between goals and accomplishment.", by : "Jim Rohn" },
    {id:"127", category:"Jim Rohn", body : "Success is nothing more than a few simple disciplines, practiced every day.", by : "Jim Rohn" },
    {id:"128", category:"Jim Rohn", body : "Success is not to be pursued; it is to be attracted by the person you become.", by : "Jim Rohn" },
    {id:"129", category:"Jim Rohn", body : "Either you run the day or the day runs you.", by : "Jim Rohn" },
    {id:"130", category:"Jim Rohn", body : "Whatever good things we build end up building us.", by : "Jim Rohn" },
    {id:"131", category:"Jim Rohn", body : "We must all suffer one of two things: the pain of discipline or the pain of regret or disappointment.", by : "Jim Rohn" },
    {id:"132", category:"Jim Rohn", body : "Take care of your body. It's the only place you have to live.", by : "Jim Rohn" },
    {id:"133", category:"Jim Rohn", body : "Don't wish it were easier, wish you were better.", by : "Jim Rohn" },
    {id:"134", category:"Jim Rohn", body : "Don't say, \"If I could, I would.\" Say, \"If I can, I will\"", by : "Jim Rohn" },
    {id:"135", category:"Jim Rohn", body : "Indecision is the thief of opportunity.", by : "Jim Rohn" },
    {id:"136", category:"Jim Rohn", body : "You cannot change your destination overnight, but you can change your direction overnight.", by : "Jim Rohn" },
    {id:"137", category:"Mark Victor Hansen", body : "Ideas attract money, time, talents, skills, energy and other complementary ideas that will bring them into reality.", by : "Mark Victor Hansen" },
    {id:"138", category:"Mark Victor Hansen", body : "I never let my subject get in the way of what I want to talk about.", by : "Mark Victor Hansen" },
    {id:"139", category:"Mark Victor Hansen", body : "I want to talk with people who care about things that matter that will make a life- changing difference.", by : "Mark Victor Hansen" },
    {id:"140", category:"Mark Victor Hansen", body : "In imagination, there's no limitation.", by : "Mark Victor Hansen" },
    {id:"141", category:"Mark Victor Hansen", body : "When your self-worth goes up, your net worth goes up with it.", by : "Mark Victor Hansen" },
    {id:"142", category:"Mark Victor Hansen", body : "Imitate until you emulate; match and surpass those who launched you. It's the highest form of thankfulness.", by : "Mark Victor Hansen" },
    {id:"143", category:"Mark Victor Hansen", body : "Your belief determines your action and your action determines your results, but first you have to believe.", by : "Mark Victor Hansen" },
    {id:"144", category:"Mark Victor Hansen", body : "The more goals you set - the more goals you get.", by : "Mark Victor Hansen" },
    {id:"145", category:"Mark Victor Hansen", body : "With vision, every person, organization and country can flourish. The Bible says, 'Without vision we perish.", by : "Mark Victor Hansen" },
    {id:"146", category:"Mark Victor Hansen", body : "Predetermine the objectives you want to accomplish. Think big, act big and set out to accomplish big results.", by : "Mark Victor Hansen" },
    {id:"147", category:"Napoleon Hill", body : "The best job goes to the person who can get it done without passing the buck or coming back with excuses.", by : "Napoleon Hill" },
    {id:"148", category:"Napoleon Hill", body : "It is always your next move.", by : "Napoleon Hill" },
    {id:"149", category:"Napoleon Hill", body : "No one can make you jealous, angry, vengeful, or greedy -- unless you let him.", by : "Napoleon Hill" },
    {id:"150", category:"Napoleon Hill", body : "Everyone enjoys doing the kind of work for which he is best suited.", by : "Napoleon Hill" },
    {id:"151", category:"Napoleon Hill", body : "The most common cause of fear of old age is associated with the possibility of poverty.", by : "Napoleon Hill" },
    {id:"152", category:"Napoleon Hill", body : "There is always room for those who can be relied upon to deliver the goods when they say they will.", by : "Napoleon Hill" },
    {id:"153", category:"Napoleon Hill", body : "Just as our eyes need light in order to see, our minds need ideas in order to conceive.", by : "Napoleon Hill" },
    {id:"154", category:"Napoleon Hill", body : "Money without brains is always dangerous.", by : "Napoleon Hill" },
    {id:"155", category:"Napoleon Hill", body : "War grows out of the desire of the individual to gain advantage at the expense of his fellow men.", by : "Napoleon Hill" },
    {id:"156", category:"Napoleon Hill", body : "Persistence is to the character of man as carbon is to steel.", by : "Napoleon Hill" },
    {id:"157", category:"Napoleon Hill", body : "Don't wait. The time will never be just right.", by : "Napoleon Hill" },
    {id:"158", category:"Napoleon Hill", body : "The ladder of success is never crowded at the top.", by : "Napoleon Hill" },
    {id:"159", category:"Napoleon Hill", body : "All great truths are simple in final analysis, and easily understood; if they are not, they are not great truths.", by : "Napoleon Hill" },
    {id:"160", category:"Napoleon Hill", body : "If you cannot do great things, do small things in a great way.", by : "Napoleon Hill" },
    {id:"161", category:"Napoleon Hill", body : "No man can succeed in a line of endeavor which he does not like.", by : "Napoleon Hill" },
    {id:"162", category:"Napoleon Hill", body : "The most interesting thing about a postage stamp is the persistence with which it sticks to its job.", by : "Napoleon Hill" },
    {id:"163", category:"Napoleon Hill", body : "It is literally true that you can succeed best and quickest by helping others to succeed.", by : "Napoleon Hill" },
    {id:"164", category:"Napoleon Hill", body : "You might well remember that nothing can bring you success but yourself.", by : "Napoleon Hill" },
    {id:"165", category:"Napoleon Hill", body : "Indecision is the seedling of fear.", by : "Napoleon Hill" },
    {id:"166", category:"Napoleon Hill", body : "Big pay and little responsibility are circumstances seldom found together.", by : "Napoleon Hill" },
    {id:"167", category:"Norman Vincent Peale", body : "Empty pockets never held anyone back. Only empty heads and empty hearts can do that.", by : "Norman Vincent Peale" },
    {id:"168", category:"Norman Vincent Peale", body : "Live your life and forget your age.", by : "Norman Vincent Peale" },
    {id:"169", category:"Norman Vincent Peale", body : "First thing every morning before you arise say out loud, \"I believe,\" three times.", by : "Norman Vincent Peale" },
    {id:"170", category:"Norman Vincent Peale", body : "There is a real magic in enthusiasm. It spells the difference between mediocrity and accomplishment.", by : "Norman Vincent Peale" },
    {id:"171", category:"Norman Vincent Peale", body : "Stand up to your obstacles and do something about them. You will find that they haven't half the strength you think they have.", by : "Norman Vincent Peale" },
    {id:"172", category:"Norman Vincent Peale", body : "We struggle with the complexities and avoid the simplicities.", by : "Norman Vincent Peale" },
    {id:"173", category:"Norman Vincent Peale", body : "Never talk defeat. Use words like hope, belief, faith, victory.", by : "Norman Vincent Peale" },
    {id:"174", category:"Norman Vincent Peale", body : "Practice hope. As hopefulness becomes a habit, you can achieve a permanently happy spirit.", by : "Norman Vincent Peale" },
    {id:"175", category:"Norman Vincent Peale", body : "If you want to get somewhere you have to know where you want to go and how to get there. Then never, never, never give up.", by : "Norman Vincent Peale" },
    {id:"176", category:"Norman Vincent Peale", body : "In every difficult situation is potential value. Believe this, then begin looking for it.", by : "Norman Vincent Peale" },
    {id:"177", category:"Norman Vincent Peale", body : "The more you lose yourself in something bigger than yourself, the more energy you will have.", by : "Norman Vincent Peale" },
    {id:"178", category:"Norman Vincent Peale", body : "Understanding can overcome any situation, however mysterious or insurmountable it may appear to be.", by : "Norman Vincent Peale" },
    {id:"179", category:"Norman Vincent Peale", body : "The mind, ever the willing servant, will respond to boldness, for boldness, in effect, is a command to deliver mental resources.", by : "Norman Vincent Peale" },
    {id:"180", category:"Norman Vincent Peale", body : "Enthusiasm releases the drive to carry you over obstacles and adds significance to all you do.", by : "Norman Vincent Peale" },
    {id:"181", category:"Norman Vincent Peale", body : "It's always too soon to quit!", by : "Norman Vincent Peale" },
    {id:"182", category:"Norman Vincent Peale", body : "Cushion the painful effects of hard blows by keeping the enthusiasm going strong, even if doing so requires struggle.", by : "Norman Vincent Peale" },
    {id:"183", category:"Norman Vincent Peale", body : "Life's blows cannot break a person whose spirit is warmed at the fire of enthusiasm.", by : "Norman Vincent Peale" },
    {id:"184", category:"Norman Vincent Peale", body : "You can be greater than anything that can happen to you.", by : "Norman Vincent Peale" },
    {id:"185", category:"Norman Vincent Peale", body : "Go forward confidently, energetically attacking problems, expecting favorable outcomes.", by : "Norman Vincent Peale" },
    {id:"186", category:"Norman Vincent Peale", body : "Believe it is possible to solve your problem. Tremendous things happen to the believer. So believe the answer will come. It will.", by : "Norman Vincent Peale" },
    {id:"187", category:"Norman Vincent Peale", body : "When you are afraid, do the thing you are afraid of and soon you will lose your fear of it.", by : "Norman Vincent Peale" },
    {id:"188", category:"Norman Vincent Peale", body : "The more you venture to live greatly, the more you will find within you what it takes to get on top of things and stay there.", by : "Norman Vincent Peale" },
    {id:"189", category:"Norman Vincent Peale", body : "If you want things to be different, perhaps the answer is to become different yourself.", by : "Norman Vincent Peale" },
    {id:"190", category:"Norman Vincent Peale", body : "Believe that you are bigger than your difficulties, for you are, indeed.", by : "Norman Vincent Peale" },
    {id:"191", category:"Ralph Waldo Emerson", body : "Beware when the great God lets loose a thinker on this planet.", by : "Ralph Waldo Emerson" },
    {id:"192", category:"Ralph Waldo Emerson", body : "Character is higher than intellect... A great soul will be strong to live, as well as to think.", by : "Ralph Waldo Emerson" },
    {id:"193", category:"Ralph Waldo Emerson", body : "Do not be too timid and squeamish about your actions. All life is an experiment.", by : "Ralph Waldo Emerson" },
    {id:"194", category:"Ralph Waldo Emerson", body : "Do not go where the path may lead, go instead where there is no path and leave a trail.", by : "Ralph Waldo Emerson" },
    {id:"195", category:"Ralph Waldo Emerson", body : "I awoke this morning with devout thanksgiving for my friends, the old and the new.", by : "Ralph Waldo Emerson" },
    {id:"196", category:"Ralph Waldo Emerson", body : "If I have lost confidence in myself, I have the universe against me.", by : "Ralph Waldo Emerson" },
    {id:"197", category:"Ralph Waldo Emerson", body : "Insist on yourself; never imitate... Every great man is unique.", by : "Ralph Waldo Emerson" },
    {id:"198", category:"Ralph Waldo Emerson", body : "Let not a man guard his dignity, but let his dignity guard him.", by : "Ralph Waldo Emerson" },
    {id:"199", category:"Ralph Waldo Emerson", body : "Nothing can bring you peace but yourself.", by : "Ralph Waldo Emerson" },
    {id:"200", category:"Ralph Waldo Emerson", body : "The only way to have a friend is to be one.", by : "Ralph Waldo Emerson" },
    {id:"201", category:"Ralph Waldo Emerson", body : "Trust men and they will be true to you; treat them greatly, and they will show themselves great.", by : "Ralph Waldo Emerson" },
    {id:"202", category:"Ralph Waldo Emerson", body : "The best effect of fine persons is felt after we have left their presence.", by : "Ralph Waldo Emerson" },
    {id:"203", category:"Ralph Waldo Emerson", body : "Every artist was first an amateur.", by : "Ralph Waldo Emerson" },
    {id:"204", category:"Ralph Waldo Emerson", body : "The reward of a thing well done is to have done it.", by : "Ralph Waldo Emerson" },
    {id:"205", category:"Robert H. Schuller", body : "Yes, you can be a dreamer and a doer too, if you will remove one word from your vocabulary: impossible.", by : "Robert H. Schuller" },
    {id:"206", category:"Robert H. Schuller", body : "You can often measure a person by the size of his dream.", by : "Robert H. Schuller" },
    {id:"207", category:"Robert H. Schuller", body : "Build a dream and the dream will build you.", by : "Robert H. Schuller" },
    {id:"208", category:"Robert H. Schuller", body : "Always look at what you have left. Never look at what you have lost.", by : "Robert H. Schuller" },
    {id:"209", category:"Robert H. Schuller", body : "If you listen to your fears, you will die never knowing what a great person you might have been.", by : "Robert H. Schuller" },
    {id:"210", category:"Robert H. Schuller", body : "Impossible situations can become possible miracles.", by : "Robert H. Schuller" },
    {id:"211", category:"Robert H. Schuller", body : "Let your imagination release your imprisoned possibilities.", by : "Robert H. Schuller" },
    {id:"212", category:"Robert H. Schuller", body : "Anyone can count the seeds in an apple, but only God can count the number of apples in a seed.", by : "Robert H. Schuller" },
    {id:"213", category:"Robert H. Schuller", body : "Most people who succeed n the face of seemingly impossible conditions are people who simply don't know how to quit.", by : "Robert H. Schuller" },
    {id:"214", category:"Robert H. Schuller", body : "Life is but a moment, death also is but another.", by : "Robert H. Schuller" },
    {id:"215", category:"Robert H. Schuller", body : "Better to do something imperfectly than to do nothing flawlessly.", by : "Robert H. Schuller" },
    {id:"216", category:"Robert H. Schuller", body : "What great thing would you attempt if you knew you could not fail?", by : "Robert H. Schuller" },
    {id:"217", category:"Robert H. Schuller", body : "The only place where your dream becomes impossible is in your own thinking.", by : "Robert H. Schuller" },
    {id:"218", category:"Robert H. Schuller", body : "Never cut a tree down in the wintertime. Never make a negative decision in the low time.", by : "Robert H. Schuller" },
    {id:"219", category:"Robert H. Schuller", body : "Problems are not stop signs, they are guidelines.", by : "Robert H. Schuller" },
    {id:"220", category:"Robert H. Schuller", body : "Let your hopes, not your hurts, shape your future.", by : "Robert H. Schuller" },
    {id:"221", category:"Robert H. Schuller", body : "Always look at what you have left. Never look at what you have lost.", by : "Robert H. Schuller" },
    {id:"222", category:"Robert T. Kiyosaki", body : "Failure defeats losers, failure inspires winners.", by : "Robert T. Kiyosaki" },
    {id:"223", category:"Robert T. Kiyosaki", body : "Your most expensive advice is the free advice you receive from your financially struggling friends and relatives.", by : "Robert T. Kiyosaki" },
    {id:"224", category:"Robert T. Kiyosaki", body : "Average investors are on the outside trying to look into the inside of the company or property they are investing in.", by : "Robert T. Kiyosaki" },
    {id:"225", category:"Robert T. Kiyosaki", body : "It's the investor who is risky, not the investment.", by : "Robert T. Kiyosaki" },
    {id:"226", category:"Robert T. Kiyosaki", body : "The idea of working all your life, saving, and putting money into a retirement account is a very slow plan.", by : "Robert T. Kiyosaki" },
    {id:"227", category:"Robert T. Kiyosaki", body : "If you don't first handle fear and desire, and you get rich, you'll be a high pay slave.", by : "Robert T. Kiyosaki" },
    {id:"228", category:"Robert T. Kiyosaki", body : "To gain more abundance a person needs more skills and needs to be more creative and cooperative.", by : "Robert T. Kiyosaki" },
    {id:"229", category:"Robert T. Kiyosaki", body : "The unique ability to take decisive action while maintaining focus on the ultimate mission is what defines a true leader.", by : "Robert T. Kiyosaki" },
    {id:"230", category:"Robert T. Kiyosaki", body : "By asking the question \"How can I afford it?\" your brain is put to work.", by : "Robert T. Kiyosaki" },
    {id:"231", category:"Thomas Edison", body : "Opportunity is missed by most people because it is dressed in overalls and looks like work.", by : "Thomas Edison" },
    {id:"232", category:"Thomas Edison", body : "My main purpose in life is to make money so I can afford to go on creating more inventions.", by : "Thomas Edison" },
    {id:"233", category:"Thomas Edison", body : "My principal business is giving commercial value to the brilliant - but misdirected ideas of others.", by : "Thomas Edison" },
    {id:"234", category:"Thomas Edison", body : "I am quite correctly described as 'more of a sponge than an inventor.", by : "Thomas Edison" },
    {id:"235", category:"Thomas Edison", body : "A good idea is never lost. Even though its originator or possessor may die, it will someday be reborn in the mind of another.", by : "Thomas Edison" },
    {id:"236", category:"Thomas Edison", body : "If we all did the things we are really capable of doing, we would literally astound ourselves.", by : "Thomas Edison" },
    {id:"237", category:"Thomas Edison", body : "I have far more respect for the person with a single idea who gets there than for the person with a thousand ideas who does nothing.", by : "Thomas Edison" },
    {id:"238", category:"Thomas Edison", body : "Many of life's failures are experienced by people who did not realize how close they were to success when they gave up.", by : "Thomas Edison" },
    {id:"239", category:"Thomas Edison", body : "Sometimes, all you need to invent something is a good imagination and a pile of junk.", by : "Thomas Edison" },
    {id:"240", category:"Thomas Edison", body : "The thing I lose patience with the most is the clock. Its hands move too fast.", by : "Thomas Edison" },
    {id:"241", category:"Thomas Edison", body : "Time is really the only capital that any human being has and the thing that he can least afford to waste or lose.", by : "Thomas Edison" },
    {id:"242", category:"Thomas Edison", body : "Whatever the mind of man creates, should be controlled by man's character.", by : "Thomas Edison" },
    {id:"243", category:"Thomas Edison", body : "Someday, man will harness the rise and fall of the tides, imprison the power of the sun, and release atomic power.", by : "Thomas Edison" },
    {id:"244", category:"Thomas Edison", body : "Until man duplicates a blade of grass, nature can laugh at his so-called scientific knowledge.", by : "Thomas Edison" },
    {id:"245", category:"Thomas Edison", body : "I believe that the science of chemistry alone almost proves the existence of an intelligent creator.", by : "Thomas Edison" },
    {id:"246", category:"Thomas Edison", body : "If parents pass enthusiasm along to their children, they will leave them an estate of incalculable value.", by : "Thomas Edison" },
    {id:"247", category:"Thomas Edison", body : "Life's most soothing things are a child's goodnight and sweet music.", by : "Thomas Edison" },
    {id:"248", category:"Thomas Jefferson", body : "I believe that every human mind feels pleasure in doing good to another.", by : "Thomas Jefferson" },
    {id:"249", category:"Thomas Jefferson", body : "The most valuable of all talents is that of never using two words when one will do.", by : "Thomas Jefferson" },
    {id:"250", category:"Thomas Jefferson", body : "Friendship is precious, not only in the shade, but in the sunshine of life.", by : "Thomas Jefferson" },
    {id:"251", category:"Thomas Jefferson", body : "It is my principle that the will of the majority should always prevail.", by : "Thomas Jefferson" },
    {id:"252", category:"Thomas Jefferson", body : "When a man assumes a public trust, he should consider himself as public property.", by : "Thomas Jefferson" },
    {id:"253", category:"Thomas Jefferson", body : "The man who fears no truths has nothing to fear from lies.", by : "Thomas Jefferson" },
    {id:"254", category:"Thomas Jefferson", body : "Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude.", by : "Thomas Jefferson" },
    {id:"255", category:"Thomas Jefferson", body : "I'm a great believer in luck, and I find the harder I work the more I have of it.", by : "Thomas Jefferson" },
    {id:"256", category:"Thomas Jefferson", body : "Never spend your money before you have it.", by : "Thomas Jefferson" },
    {id:"257", category:"Thomas Jefferson", body : "Never trouble another for what you can do for yourself.", by : "Thomas Jefferson" },
    {id:"258", category:"Thomas Jefferson", body : "Nothing gives one person so much advantage over another as to remain always cool and unruffled under all circumstances.", by : "Thomas Jefferson" },
    {id:"259", category:"Thomas Jefferson", body : "Walking is the best possible exercise. Habituate yourself to walk very far.", by : "Thomas Jefferson" },
    {id:"260", category:"W. Clement Stone", body : "Aim for the moon. If you miss, you may hit a star.", by : "W. Clement Stone" },
    {id:"261", category:"W. Clement Stone", body : "Be careful the environment you choose for it will shape you; be careful the friends you choose for you will become like them.", by : "W. Clement Stone" },
    {id:"262", category:"W. Clement Stone", body : "If there is something to gain and nothing to lose by asking, by all means ask!", by : "W. Clement Stone" },
    {id:"263", category:"W. Clement Stone", body : "Self-suggestion makes you master of yourself.", by : "W. Clement Stone" },
    {id:"264", category:"W. Clement Stone", body : "Tell everyone what you want to do and someone will want to help you do it.", by : "W. Clement Stone" },
    {id:"265", category:"W. Clement Stone", body : "Thinking will not overcome fear but action will.", by : "W. Clement Stone" },
    {id:"266", category:"W. Clement Stone", body : "Truth will always be truth, regardless of lack of understanding, disbelief or ignorance.", by : "W. Clement Stone" },
    {id:"267", category:"W. Clement Stone", body : "When we direct our thoughts properly, we can control our emotions.", by : "W. Clement Stone" },
    {id:"268", category:"W. Clement Stone", body : "You affect your subconscious mind by verbal repetition.", by : "W. Clement Stone" },
    {id:"269", category:"W. Clement Stone", body : "Definiteness of purpose is the starting point of all achievement", by : "W. Clement Stone" },
    {id:"270", category:"W. Clement Stone", body : "Success is achieved and maintained by those who try and keep trying.", by : "W. Clement Stone" },
    {id:"271", category:"Zig Ziglar", body : "You are the only person on earth who can use your ability.", by : "Zig Ziglar" },
    {id:"272", category:"Zig Ziglar", body : "When you put faith, hope and love together, you can raise positive kids in a negative world.", by : "Zig Ziglar" },
    {id:"273", category:"Zig Ziglar", body : "There has never been a statue erected to honor a critic.", by : "Zig Ziglar" },
    {id:"274", category:"Zig Ziglar", body : "Failure is a detour, not a dead-end street.", by : "Zig Ziglar" },
    {id:"275", category:"Zig Ziglar", body : "What you get by achieving your goals is not as important as what you become by achieving your goals.", by : "Zig Ziglar" },
    {id:"276", category:"Zig Ziglar", body : "Happiness is not pleasure, it is victory.", by : "Zig Ziglar" },
    {id:"277", category:"Zig Ziglar", body : "Every sale has five basic obstacles: no need, no money, no hurry, no desire, no trust.", by : "Zig Ziglar" },
    {id:"278", category:"Zig Ziglar", body : "It's not what you've got, it's what you use that makes a difference.", by : "Zig Ziglar" },
    {id:"279", category:"Zig Ziglar", body : "Success is the maximum utilization of the ability that you have.", by : "Zig Ziglar" },
    {id:"280", category:"Zig Ziglar", body : "Winning is not everything, but the effort to win is.", by : "Zig Ziglar" },
    {id:"281", category:"Zig Ziglar", body : "Efficiency is doing things right. Effectiveness is doing the right thing.", by : "Zig Ziglar" },
    {id:"282", category:"Zig Ziglar", body : "The person who will not stand for something will fall for anything.", by : "Zig Ziglar" },
    {id:"283", category:"Zig Ziglar", body : "It's your attitude not your aptitude that determines your altitude.", by : "Zig Ziglar" },
    {id:"284", category:"Zig Ziglar", body : "You do not pay the price of success, you enjoy the price of success.", by : "Zig Ziglar" },
    {id:"285", category:"Zig Ziglar", body : "All resources are not obvious; great managers find and develop available talent.", by : "Zig Ziglar" },
    {id:"286", category:"Zig Ziglar", body : "A goal properly set is halfway reached.", by : "Zig Ziglar" },
    {id:"287", category:"Zig Ziglar", body : "Positive thinking will let you do everything better than negative thinking will.", by : "Zig Ziglar" },
    {id:"289", category:"Taking Action", body : "You do not have to be great to start, but you have to start to be great.", by : "Joe Sabah " },
    {id:"290", category:"Taking Action", body : "You may be disappointed if you fail, but you are doomed if you never try.", by : "Beverly Sills " },
    {id:"291", category:"Taking Action", body : "Anything you can do needs to be done, so pick up the tool of your choice and get started.", by : "Ben Linder " },
    {id:"292", category:"Taking Action", body : "He who is outside the door has already a good part of his journey behind him.", by : "Dutch Proverb" },
    {id:"293", category:"Taking Action", body : "Vision without action is merely a dream. Action without vision just passes the time. Vision with action can change the world.", by : "Joel Arthur Barker" },
    {id:"294", category:"Taking Action", body : "Learning new things won’t help the person who isn’t using what he already knows.", by : "Anonymous" },
    {id:"295", category:"Taking Action", body : "No one knows what he can do until he tries.", by : "Pubilius Syrus" },
    {id:"296", category:"Taking Action", body : "The great aim of education is not knowledge, but action.", by : "Herbert Spencer" },
    {id:"297", category:"Taking Action", body : "It’s not what you know that makes the difference. It’s what you DO with what you know that makes the difference.", by : "Dr. Julie White" },
    {id:"298", category:"Taking Action", body : "You will get no more out of life than you put into it.", by : "William J.H. Boetcker" },
    {id:"299", category:"Taking Action", body : "What one does is what counts. Not what one had the intention of doing.", by : "Pablo Picasso" },
    {id:"300", category:"Taking Action", body : "Action will remove the doubt that theory can’t solve.", by : "Tehyi Hsieh" },
    {id:"301", category:"Taking Action", body : "Often greater risk is involved in postponement than in making a wrong decision.", by : "H.A. Hopf" },
    {id:"302", category:"Taking Action", body : "You can’t ‘try’ to do things; you simply must DO them.", by : "Ray Bradbury" },
    {id:"303", category:"Taking Action", body : "Jump into the middle of things, get your hands dirty, fall flat on your face, and then reach for the stars.", by : "Joan L. Curcio" },
    {id:"304", category:"Taking Action", body : "A wise man will make more opportunities than he finds.", by : "Francis Bacon" },
    {id:"305", category:"Taking Action", body : "Your actions, and your action alone, determines your worth.", by : "Johann G. Fichte" },
    {id:"306", category:"Taking Action", body : "The way to get ahead is to start now.", by : "William Feather" },
    {id:"307", category:"Taking Action", body : "Nothing will kill a deal like time.", by : "Joe Martin" },
    {id:"308", category:"Taking Action", body : "Move them forward, or move them out.", by : "Art Sobczak" },
    {id:"309", category:"Adversity", body : "Adversity is an experience, not a final act.", by : "Dr. Michael Leboeuf" },
    {id:"310", category:"Adversity", body : "If you don’t fail now and again, it’s a sign you’re playing it safe.", by : "Woody Allen" },
    {id:"311", category:"Adversity", body : "If you don’t fail now and again, it’s a sign you’re playing it safe.", by : "Woody Allen" },
    {id:"312", category:"Adversity", body : "Failure is an event, never a person.", by : "William D. Brown" },
    {id:"313", category:"Adversity", body : "Experience is not what happens to you. Experience is what you do with what happens to you.", by : "Aldous Huxley" },
    {id:"314", category:"Adversity", body : "Success is getting up one more time than you fall down.", by : "Doc Blakely" },
    {id:"315", category:"Adversity", body : "We must accept finite disappointment, but we must never lose infinite hope.", by : "Martin Luther King" },
    {id:"316", category:"Adversity", body : "If you want to increase your success rate, double your failure rate.", by : "Thomas Watson" },
    {id:"317", category:"Adversity", body : "Bad times have a scientific value. These are occasions a good learner would not miss.", by : "Ralph Waldo Emerson" },
    {id:"318", category:"Adversity", body : "There are two ways of meeting difficulties: you alter the difficulties or you alter yourself meeting them.", by : "Phyllis Bottome" },
    {id:"319", category:"Adversity", body : "The crisis of today is the joke of tomorrow.", by : "H.G. Wells" },
    {id:"320", category:"Adversity", body : "Success is going from failure to failure without a loss of enthusiasm.", by : "Sir Winston Churchill" },
    {id:"321", category:"Adversity", body : "While one person hesitates because he feels inferior, the other is busy making mistakes and becoming superior.", by : "Henry C. Link" },
    {id:"322", category:"Adversity", body : "We are often more frightened than hurt; and we suffer more from imagination than from reality.", by : "Anonymous" },
    {id:"323", category:"Adversity", body : "People are known as much for the quality of their failures as the quality of the successes.", by : "Mark McCormack" },
    {id:"324", category:"Adversity", body : "In every difficult situation is potential value. Believe this, then begin looking for it.", by : "Norman Vincent Peale" },
    {id:"325", category:"Adversity", body : "Life is 10% what happens to you and 90% how you react to it.", by : "Lou Holtz" },
    {id:"326", category:"Adversity", body : "It may not be your fault for being down, but it’s got to be your fault for not getting up.", by : "Steve Davis" },
    {id:"327", category:"Adversity", body : "Pain is inevitable. Suffering is optional.", by : "Unknown" },
    {id:"328", category:"Adversity", body : "Worry is like a rocking chair; you expend a lot of energy and never get anywhere.", by : "George Cummings" },
    {id:"329", category:"Adversity", body : "I can’t say I was ever lost, but I was bewildered once for three days.", by : "Daniel Boone" },
    {id:"330", category:"Attitude", body : "Of all the things you wear, your expression is the most important.", by : "Unknown" },
    {id:"331", category:"Attitude", body : "Attitudes are more important than facts.", by : "Dr. Karl Menninger" },
    {id:"332", category:"Attitude", body : "Outlook determines outcome; attitude determines action.", by : "Warren W. Wiersbe" },
    {id:"333", category:"Attitude", body : "It is easier to act yourself into feeling, than to feel yourself into acting.", by : "William James" },
    {id:"334", category:"Attitude", body : "If you think you can or you can’t, you’re always right.", by : "Henry Ford" },
    {id:"335", category:"Attitude", body : "If you want to change attitudes, start with a change in behavior.", by : "William Glasser" },
    {id:"336", category:"Attitude", body : "Enthusiasm is the greatest asset in the world. It beats money, power, and influence.", by : "Henry Chester" },
    {id:"337", category:"Attitude", body : "A man can succeed at almost anything for which he has unlimited enthusiasm.", by : "Charles M. Schwab" },
    {id:"338", category:"Attitude", body : "Once you say you’re going to settle for second, that’s what happens to you.", by : "John F. Kennedy" },
    {id:"339", category:"Attitude", body : "Nothing great was ever achieved without enthusiasm.", by : "Ralph Waldo Emerson" },
    {id:"340", category:"Attitude", body : "Life is a mirror and will reflect back to the thinker what he thinks into it.", by : "Ernest Holmes" },
    {id:"341", category:"Attitude", body : "What we see depends mainly on what we look for.", by : "John Lubbock" },
    {id:"342", category:"Attitude", body : "If you must doubt anything, doubt your perceived limitations.", by : "Unknown" },
    {id:"343", category:"Attitude", body : "All the technology in the world will never replace a positive attitude.", by : "Harvey Mackay" },
    {id:"344", category:"Think Big", body : "Dreams are powerful reflections of your actual growth potential.", by : "Dr. Denis Waitley" },
    {id:"345", category:"Think Big", body : "Great minds have purposes, others have wishes.", by : "Washington Irving" },
    {id:"346", category:"Think Big", body : "If you have the will to win, you have achieved half your success; if you don’t, you have achieved half your failure.", by : "David V.A. Ambrose" },
    {id:"347", category:"Think Big", body : "Life is a great big canvas, and you should throw all the paint on it you can.", by : "Danny Kaye" },
    {id:"348", category:"Think Big", body : "Wealth is largely the result of habit.", by : "John Jacob Astor" },
    {id:"349", category:"Think Big", body : "We would accomplish many more things if we did not think of them as impossible.", by : "C. Malesherbez" },
    {id:"350", category:"Goals", body : "You must have long term goals to keep you from being frustrated by short term failures.", by : "Charles C. Noble" },
    {id:"351", category:"Goals", body : "Nothing is as necessary for success as the single-minded pursuit of an objective.", by : "Fred Smith" },
    {id:"352", category:"Goals", body : "More people fail because of lack of purpose than do because of a lack of talent.", by : "Bill Sunday" },
    {id:"353", category:"Goals", body : "Success in sales, and life, is a series of tiny victories.", by : "Don Brummer" },
    {id:"354", category:"Goals", body : "Don’t make your goals too easy; you’ll be cheating yourself.", by : "Alec Mackenzie" },
    {id:"355", category:"Goals", body : "When you reach for the stars, you may not quite get one, but you won’t come up with a handful of mud, either.", by : "Leo Burnett" },
    {id:"356", category:"Goals", body : "If you’re surprised by what you achieve, you’re not setting your goals high enough.", by : "Elena Hesse" },
    {id:"357", category:"Learning", body : "To continue learning is to embrace the process of trial and error at higher and higher levels.", by : "Michael Gelb" },
    {id:"358", category:"Learning", body : "Real ongoing lifelong education doesn’t answer questions, it provokes them.", by : "Luci Swindol" },
    {id:"359", category:"Learning", body : "An investment in knowledge pays the best interest.", by : "Ben Franklin" },
    {id:"360", category:"Learning", body : "No man really becomes a fool until he stops asking questions.", by : "Charles P. Steinmetz" },
    {id:"361", category:"Learning", body : "Forget the times of your distress, but never forget what they taught you.", by : "Herbert Gasser" },
    {id:"362", category:"Learning", body : "A fact may be the smallest unit of information, but a story is the smallest unit of meaning.", by : "Kieran Egan" },
    {id:"363", category:"Learning", body : "Learn as if you were going to live forever. Live as if you were going to die tomorrow.", by : "Unknown" },
    {id:"364", category:"Learning", body : "To be happy, drop the words ‘if only’ and substitute instead the words ‘next time’.", by : "Smiley Blanton" },
    {id:"365", category:"Learning", body : "What we actually learn, from any given set of circumstances, determines whether we become increasingly powerless or more powerful.", by : "Blaine Lee" },
    {id:"366", category:"Persistence", body : "Effort only fully releases its reward after a person refuses to quit.", by : "Napolean Hill" },
    {id:"367", category:"Persistence", body : "The person who wins may have been counted out several times, but he didn’t hear the referee.", by : "H.E. Jansen" },
    {id:"368", category:"Persistence", body : "Life is a grindstone. But whether it grinds us down or polishes us up depends on us.", by : "L. Thomas Holdcroft" },
    {id:"369", category:"Persistence", body : "The thing we call ‘failure’ is not falling down, but staying down.", by : "Mary Pickford" },
    {id:"370", category:"Persistence", body : "If you are doing your best, you will not have time to worry about failure.", by : "Robert Hilyer" },
    {id:"371", category:"Persistence", body : "Everyone who got where he is had to begin where he was.", by : "Robert Louis Stevenson" },
    {id:"372", category:"Persistence", body : "Only those who have the patience to do simple things perfectly will acquire the skill to do difficult things easily.", by : "Johann Friedrich" },
    {id:"373", category:"Persistence", body : "We can learn to soar only in direct proportion to our determination to rise above the doubt and transcend the limitations.", by : "David McNally" },
    {id:"374", category:"Preparation", body : "To be prepared is to have no anxiety.", by : "Korean proverb" },
    {id:"375", category:"Preparation", body : "Chance favors the prepared mind.", by : "Louis Pasteur" },
    {id:"376", category:"Preparation", body : "In all things, success depends upon previous preparation, and without such preparation, there is failure.", by : "Confucius" },
    {id:"377", category:"Preparation", body : "I skate to where the puck is going to be, not where it has been.", by : "Wayne Gretzky" },
    {id:"378", category:"Preparation", body : "Your future depends on many things, but mostly on you.", by : "Frank Tyger" },
    {id:"379", category:"Preparation", body : "My whole life is waiting for the questions to which I have prepared answers.", by : "Tom Stoppard" },
    {id:"380", category:"Taking Risks", body : "Unless you try to do something beyond what you have already mastered, you will never grow.", by : "Charles Tremendous Jones" },
    {id:"381", category:"Taking Risks", body : "A ship in port is safe, but that’s not what ships are built for.", by : "John Shedd" },
    {id:"382", category:"Taking Risks", body : "If you’re never scared, embarrassed, or hurt, it means you never take any chances.", by : "Julia Sorel" },
    {id:"383", category:"Taking Risks", body : "Only those who risk going too far can possibly find out how far one can go.", by : "T.S. Eliot" },
    {id:"384", category:"Taking Risks", body : "Why not go out on a limb. Isn’t that where the fruit is?", by : "Frank Scully" },
    {id:"385", category:"Taking Risks", body : "Progress always involves risk. You can’t steal second base with your foot on first.", by : "Frederick Wilcox" },
    {id:"386", category:"Taking Risks", body : "If you limit your actions to things that nobody can possibly find fault with, you will not do much.", by : "Charles Lutwidge Dodgson" },
    {id:"387", category:"Taking Risks", body : "There’s as much risk in doing nothing as in doing something.", by : "Trammell Crow" },
    {id:"388", category:"Taking Risks", body : "Too many people are thinking of security rather than opportunity.", by : "James F. Byrnes" },
    {id:"389", category:"Taking Risks", body : "People who take risks are the people you’ll lose against.", by : "John Sculley" },
    {id:"390", category:"Taking Risks", body : "The person who makes no mistakes does not usually make anything.", by : "Bishop W.C. Magee" },
    {id:"391", category:"Taking Risks", body : "The only failure which lacks dignity is the failure to try.", by : "Malcom F. MacNeil" },
    {id:"393", category:"Taking Risks", body : "I think we should follow one simple rule: If we can take the worst, take the risk.", by : "Dr. Joyce Brothers" },
    {id:"394", category:"Taking Risks", body : "The greatest mistake you can make is to be continually fearing you will make one.", by : "Elbert Hubbard" },
    {id:"395", category:"Taking Risks", body : "Use action to cure fear and gain confidence. Do what you fear and fear disappears. Just try it and see.", by : "David Schwartz" },
    {id:"397", category:"Taking Risks", body : "What would you attempt to do if you knew you could not fail?", by : "Dr. Robert Schuller" },
    {id:"398", category:"Work", body : "Much good work is lost for the lack of a little more.", by : "Edward H. Harriman" },
    {id:"399", category:"Work", body : "The more I want to get something done, the less I call it work.", by : "Richard Bach" },
    {id:"400", category:"Work", body : "The world is full of willing people. Some willing to work, the others willing to let them.", by : "Robert Frost" },
    {id:"401", category:"Work", body : "You may have the loftiest goals, the highest ideals, the noblest dreams, but remember this, nothing works unless you do.", by : "Nido Quebein" },
    {id:"402", category:"Work", body : "Even if you are on the right track, you will get run over if you just sit there.", by : "Will Rogers" },
    {id:"403", category:"Work", body : "There are no shortcuts to any place worth going.", by : "Beverly Sills" },
    {id:"404", category:"Work", body : "He who is afraid of doing too much always does too little.", by : "German proverb" },
    {id:"396", category:"Work", body : "Unless a man undertakes more than he possibly can do, he will never do all he can do.", by : "Henry Drummond" },
    {id:"396", category:"Work", body : "When we do more than we are paid to do, eventually we will be paid more for what we do.", by : "Zig Ziglar" },
    {id:"396", category:"Work", body : "Opportunity is missed by most people because it is dressed in overalls and looks like work.", by : "Thomas Edison" },
    {id:"396", category:"Work", body : "The best preparation for good work tomorrow is good work today.", by : "Elbert Hubbard" },
    {id:"396", category:"Work", body : "People forget how fast you did a job, but they remember how well you did it.", by : "Howard W. Newton" },
    {id:"396", category:"Responsibility", body : "", by : "" },
    {id:"396", category:"Responsibility", body : "", by : "" },
    {id:"396", category:"Responsibility", body : "", by : "" },
    
    
]

export default Data;